tag: dev

apiprofesores:
  replicaCount: 1
  image: okteto.dev/apiprofesores

mongoUrl: mongodb://mongo/test

AWS_ACCESS_KEY_SERVICIO_PROFESORES: sedeberiasobreescribirconelhelmdeloktetopipeline
AWS_SECRET_ACCESS_KEY_SERVICIO_PROFESORES: sedeberiasobreescribirconelhelmdeloktetopipeline
