version: '3.8'

services:
  api:
    build: .
    depends_on: 
      - db
    volumes:
      - /app

  db:
    image: mongo:latest
    expose:
      - "27017"
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: