apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiprofesores
  labels:
    {{- include "profesores.labels" . | nindent 4 }}
    app.kubernetes.io/component: apiprofesores
spec:
  replicas: {{ .Values.apiprofesores.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: apiprofesores
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apiprofesores
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: apiprofesores
          image: {{ .Values.apiprofesores.image }}:{{ .Values.tag }}
          env:
            - name: MONGO_URL_SERVICIO_PROFESORES
              valueFrom:
                secretKeyRef:
                  name: mongodbservicioprofesores
                  key: mongo_url
            - name: AWS_ACCESS_KEY_SERVICIO_PROFESORES
              value: {{ .Values.AWS_ACCESS_KEY_SERVICIO_PROFESORES }}
            - name: AWS_SECRET_ACCESS_KEY_SERVICIO_PROFESORES
              value: {{ .Values.AWS_SECRET_ACCESS_KEY_SERVICIO_PROFESORES }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /apiprofesores/v1/healthz
              port: 3000
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /apiprofesores/v1/healthz
              port: 3000
