apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "frontend.labels" . | nindent 4 }}
type: Opaque
data:
  mongo_url: {{ .Values.mongoUrl | b64enc }}