apiVersion: v1
kind: Secret
metadata:
  name: mongodbservicioprofesores
  labels:
    app.kubernetes.io/component: mongodbservicioprofesores
    {{- include "profesores.labels" . | nindent 4 }}
type: Opaque
data:
  mongo_url: {{ .Values.mongoUrl | b64enc }}